### ISSUE TITLE
Fix Windows Build

### ISSUE THREAD

**Issue by terkelg** [terkelg/tiny-glob#15]
I don't have access to a windows machine

**Comment by mubaidr** [comment]
I am working on this issue, will keep posting updates here.

**Comment by terkelg** [comment]
Thanks @mubaidr! Much appreciated

**Comment by mubaidr** [comment]
I am also adding eslint, prettier config besides editor config to make the code more readable and standard. Is it ok?

**Comment by terkelg** [comment]
I would prefer just the fix - we one thing at a time :-)

**Comment by mubaidr** [comment]
Sure, then I will open another pull request with just the fix.

**Comment by mubaidr** [comment]
Test run fine in latest commit!

**Comment by terkelg** [comment]
Fixed in PR #22 (696054d7208a16b52ed8fa97ece5c01b2d3ca317)
