### ISSUE TITLE
File name includes part of file Path

### ISSUE THREAD

**Issue by mubaidr** [terkelg/tiny-glob#16]
**Code:**
```js
const val = 'd:\current\PROJECT_ROOT\data\sample'
const validImageFormats = ['jpg', 'jpeg', 'png']

tinyGlob(`${val}/**/*.{${validImageFormats.join(',')}}`, {
          filesOnly: true
        })
        .then(files => {
          console.log(files) //Should contain only file names :(
        })
        .catch(err => {
          console.log(err)
        })
```

**Expected Output:**
`files = ['blah.jpg', 'nope.jpeg', 'yo.png']`

**Actual Output:**
`files = ['data\sample\blah.jpg', 'data\sample\nope.jpeg', 'data\sample\yo.png']`

**Environment Info:**
Windows 10
Electron.js with Node.js version 8.9.2

**Additional Info:**
Tests also fails on Windows 10

**Comment by terkelg** [comment]
I think this is related to #15

**Comment by mubaidr** [comment]
Fixed in: https://github.com/terkelg/tiny-glob/issues/15
