### ISSUE TITLE
Benchmark against picomatch

### ISSUE THREAD

**Issue by styfle** [terkelg/tiny-glob#33]
There's a new contender: https://github.com/micromatch/picomatch

It might be good to compare performance 😃

**Comment by terkelg** [comment]
Hi @styfle, thanks for the heads up. I saw it the other day and it seems to use the same technique as tiny-glob 🤔. Could be fun to test, but the main focus of tiny-glob will always be simplicity 👍

**Comment by styfle** [comment]
I just realized picomatch doesn’t do fs operations so I guess they’re not really comparable 🤷‍♂️ 

I’ll close this.
