### ISSUE TITLE
Not working for typescript

### ISSUE THREAD

**Issue by beeing** [terkelg/tiny-glob#34]
After updating to latest version, typescript compiler will throw error on:

```
import * as glob from 'tiny-glob'
```

But this is fine in older version.

**Comment by terkelg** [comment]
I don't use TypeScript myself. Can you help and try to have a look at this?

**Comment by beeing** [comment]
Ok, I've tried fixing it and all we need is just replace `=` to `default`

```
export default glob
```

and to use:
```
import glob from 'tiny-glob'
```

**Comment by armano2** [comment]
you can use it like this:

import glob = require('tiny-glob');

**Comment by terkelg** [comment]
Thanks @beeing and @armano2. I assume no changes are needed in the source code then?

**Comment by armano2** [comment]
nope, you can add this to documentation for newcomers

**Comment by beeing** [comment]
That works too. Thanks @armano2.

Only thing is the import statement looks different from the others using `from` keyword.
