### ISSUE TITLE
Absolute paths provided as the source are changed and error out

### ISSUE THREAD

**Issue by rdmurphy** [terkelg/tiny-glob#35]
Hello!

Big fan of the speed gains here, but hit a snag when I was migrating a project away from `fast-glob`. Due to how `tiny-glob` defaults to `.` as the `cwd` if you don't pass anything in, it causes the `path.join` call [within `walk`](https://github.com/terkelg/tiny-glob/blob/master/index.js#L12) to accidentally break the absolute path that was provided as the `src`.

In other words, when I pass in something like:

```
/hello/absolute/path/here/
```

It gets turned into this by that `join` due to that `.` being prepended to the file path:

```
hello/absolute/path/here/
```

Which then throws an error, because that path does not exist.

Not sure how major of a change it'd be, but it may be worth considering hitting a provided source with [`path.isAbsolute`](https://nodejs.org/api/path.html#path_path_isabsolute_path) and skip the `cwd` prepend if it returns `true`?

I didn't check `node-glob`, but it does [appear to be how `fast-glob` approaches this situation](https://github.com/mrmlnc/fast-glob/blob/318b00b6310e0a76d8325a0afb6043ac7a1dc419/src/utils/path.ts#L20-L28).

(Somewhat related, but `fast-glob` also uses [`process.cwd()`](https://nodejs.org/api/process.html#process_process_cwd) instead of defaulting to the string dot `.` for `cwd`, which may also be a bit more resilient to any other weird interpretations of that pathing.)

Happy to take a swing at this as well if you're interested. Thank you!

**Comment by terkelg** [comment]
Hi @rdmurphy

Thank you for the kind words and for the profound issue description - appreciate it!
I wonder if this is related to #28. Can you maybe have a look at this? I would love to have someone to help maintain `tiny-glob`. I can add you to the repo if you're keen? 

Thanks,
Terkel

**Comment by ForsakenHarmony** [comment]
oh this was ignored for months now 🙃
was debugging for a long time to figure out where it comes from and what's causing it

https://github.com/terkelg/tiny-glob/blob/master/index.js#L13

it's this line

```js
> path.join('.', '/wew')
'wew'
```

**Comment by lukeed** [comment]
Thanks for the bump & investigation @ForsakenHarmony 👏 `path.resolve` should be there instead, ya?

**Comment by rdmurphy** [comment]
I mentioned it up in the first post of the issue, but I think the funkiness is coming from having an actual dot `.` as the default `cwd` value. I think having it default to `process.cwd()` instead + skipping the joining of `cwd` if it's not an absolute path would clear it up with the current code.

**Comment by lukeed** [comment]
Ah, sorry. I dont think I ever looked at this issue.

`process.cwd() === resolve('.')` so that's not the problem
