### ISSUE TITLE
Doesn't match files without glob

### ISSUE THREAD

**Issue by RedHatter** [terkelg/tiny-glob#36]
When the `cwd` option is set tiny-glob will only match patterns that have a glob in it. Without the `cwd` option everything works as intended.

src/index.js

    const glob = require('tiny-glob');

    (async function(){
        let withGlob = await glob('*.js', { cwd: 'src' });
        let withoutGlob = await glob('index.js', { cwd: 'src' });
        console.log(withGlob, withoutGlob)
    })();

The above logs `[ 'index.js' ] []`

**Comment by lukeed** [comment]
Looks like this is the culprit: https://github.com/terkelg/tiny-glob/blob/master/index.js#L55

The existence check should join the `opts.cwd` with the `str`
