### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by brodybits** [terkelg/tiny-glob#51]
Hi @terkelg I was wondering if you have any future plans in the works?

Just curious.

I am thinking it could be really nice to use this library in Prettier, they seem to have struggled with the other glob libraries.

**Comment by terkelg** [comment]
I would love to have Prettier use tiny-glob. I am working on a new version and complete rewrite of tiny-glob in my spare time. It's going to use a new and more robust glob-to-regex engine. The library in its current state is a bit buggy.

**Comment by tunnckoCore** [comment]
I just realized that there isn't no way to ignore with this library? I can't understand how so many people are even using it in first place. Don't want to offending you, just realized that you must be more explicit with your globs when you're using this lib.

Waiting to see the new version. :)

**Comment by terkelg** [comment]
I don't think being explicit is bad. The library works for my use cases and it's available for whoever finds it useful. I don't force anyone to use it. Please stay on topic

**Comment by tunnckoCore** [comment]
@terkelg true. I'm all in for explicitness. Probably should mention it in the docs too :) :P
