### ISSUE TITLE
[DEP0128] DeprecationWarning

### ISSUE THREAD

**Issue by tscpp** [terkelg/tiny-glob#65]
Using non-relative paths in the 'main' field in' package.json' is deprecated.

```
(node:16276) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\elias\Projects\kolint\node_modules\tiny-glob\package.json' of 'src/index.js'. Please either fix that or report it to the module author.
```

**Comment by Jenthan** [comment]
(node:16276) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\elias\Projects\kolint\node_modules\tiny-glob\package.json' of 'src/index.js'. Please either fix that or report it to the module author.

how to fixed this error ????

**Comment by lukeed** [comment]
Upgrade to 0.2.9

**Comment by Jenthan** [comment]
what package upgrade ????
