### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by JounQin** [terkelg/tiny-glob#88]
If so, please archive this repository and deprecate the npm package?

**Comment by terkelg** [comment]
It’s not

**Comment by JounQin** [comment]
😅 The last commit is 3 years ago, and a lot of issues are unresolved.

**Comment by lukeed** [comment]
You're conflating activity with functionality / utility

**Comment by JounQin** [comment]
> You're conflating activity with functionality / utility

As I mentioned above, the functionality is buggy, a lot of important issues unresolved.
